from pathlib import Path

p = Path("src/offscreen/streaming-pdf-exporter.ts")
text = p.read_text()
text = text.replace(
    'import { SequentialRasterPdfWriter } from "./streaming-pdf-writer";',
    'import {\n  SequentialRasterPdfWriter,\n  recoverStreamingPdfWriterState,\n} from "./streaming-pdf-writer";',
    1,
)
marker = 'function cancelledError(jobId: string): Error {'
insert = '''function storagePressurePause(\n  jobId: string,\n  pageIndex: number,\n  availableBytes: number,\n  requiredBytes: number,\n): Error {\n  return createWebCapRuntimeError(\n    createWebCapError({\n      code: "E_STORAGE_QUOTA",\n      stage: "storage",\n      message: "PDF export paused at a durable page boundary because local storage is under pressure.",\n      userMessageKey: "errors.storageQuota",\n      retryable: true,\n      fallbackAllowed: false,\n      causeCode: "StreamingPdfStoragePressurePaused",\n      safeContext: {\n        jobId: jobId.slice(0, 24),\n        pageIndex,\n        availableBytes,\n        requiredBytes,\n      },\n    }),\n  );\n}\n\nfunction resumableStorageError(error: unknown): boolean {\n  if (typeof error !== "object" || error === null || !("data" in error)) return false;\n  const data = (error as { data?: { code?: unknown; retryable?: unknown; stage?: unknown } }).data;\n  return (\n    data?.retryable === true &&\n    data.stage === "storage" &&\n    (data.code === "E_STORAGE_QUOTA" || data.code === "E_STORAGE_WRITE")\n  );\n}\n\n'''
text = text.replace(marker, insert + marker, 1)
old = '''    const startedAt = nowMilliseconds(this.environment);\n    await this.checkpoints.delete(payload.jobId).catch(() => false);\n\n    let output;\n    try {\n      output = await this.spool.createOutput(payload.outputArtifactId);\n    } catch (error) {\n      if (isPdfSpoolFallbackAllowed(error)) {\n        return this.fallback.export(payload, reportProgress);\n      }\n      throw error;\n    }\n\n    const writerPages = payload.pages ?? defaultEditorPages(payload);\n    if (writerPages.length === 0) {\n      await output.abort().catch(() => undefined);\n      throw exportError(\n        "PDF export requires at least one selected page.",\n        "StreamingPdfPagesMissing",\n      );\n    }\n    const writer = new SequentialRasterPdfWriter(output, writerPages.length);\n    const rasterReferences = new Set<string>();'''
new = '''    const startedAt = nowMilliseconds(this.environment);\n    const writerPages = payload.pages ?? defaultEditorPages(payload);\n    if (writerPages.length === 0) {\n      throw exportError(\n        "PDF export requires at least one selected page.",\n        "StreamingPdfPagesMissing",\n      );\n    }\n\n    let output;\n    let writer: SequentialRasterPdfWriter | undefined;\n    let startOutputIndex = 0;\n    const durableCheckpoint = await this.checkpoints.get(payload.jobId).catch(() => undefined);\n    if (\n      durableCheckpoint !== undefined &&\n      durableCheckpoint.outputArtifactId === payload.outputArtifactId &&\n      durableCheckpoint.totalPages === writerPages.length &&\n      durableCheckpoint.pagesWritten <= writerPages.length &&\n      this.spool.resumeOutput !== undefined\n    ) {\n      try {\n        const persisted = await this.spool.read(durableCheckpoint.spoolReference);\n        if (persisted.size < durableCheckpoint.byteLength) {\n          throw exportError(\n            "The streamed PDF spool is shorter than its writer checkpoint.",\n            "StreamingPdfResumeSpoolTruncated",\n          );\n        }\n        const durableBlob = persisted.slice(0, durableCheckpoint.byteLength, "application/pdf");\n        const resume = await recoverStreamingPdfWriterState(\n          durableBlob,\n          durableCheckpoint.pagesWritten,\n          writerPages.length,\n        );\n        output = await this.spool.resumeOutput(\n          durableCheckpoint.spoolReference,\n          durableCheckpoint.byteLength,\n        );\n        writer = new SequentialRasterPdfWriter(output, writerPages.length, resume);\n        startOutputIndex = durableCheckpoint.pagesWritten;\n      } catch {\n        await this.spool.delete(durableCheckpoint.spoolReference).catch(() => undefined);\n        await this.checkpoints.delete(payload.jobId).catch(() => false);\n      }\n    } else if (durableCheckpoint !== undefined) {\n      await this.spool.delete(durableCheckpoint.spoolReference).catch(() => undefined);\n      await this.checkpoints.delete(payload.jobId).catch(() => false);\n    }\n\n    if (writer === undefined) {\n      try {\n        output = await this.spool.createOutput(payload.outputArtifactId);\n      } catch (error) {\n        if (isPdfSpoolFallbackAllowed(error)) {\n          return this.fallback.export(payload, reportProgress);\n        }\n        throw error;\n      }\n      writer = new SequentialRasterPdfWriter(output, writerPages.length);\n    }\n    const rasterReferences = new Set<string>();'''
if old not in text:
    raise SystemExit("streamer initialization marker missing")
text = text.replace(old, new, 1)
old = '      for (const [outputIndex, entry] of pagePixelRanges.entries()) {\n        const { page, pixelXRange, pixelYRange } = entry;'
new = '''      for (let outputIndex = startOutputIndex; outputIndex < pagePixelRanges.length; outputIndex += 1) {\n        const entry = pagePixelRanges[outputIndex];\n        if (entry === undefined) {\n          throw exportError(\n            "A streamed PDF page plan is unavailable during recovery.",\n            "StreamingPdfRecoveryPageMissing",\n          );\n        }\n        const { page, pixelXRange, pixelYRange } = entry;\n        const estimatedPageBytes = Math.max(\n          1,\n          Math.ceil(pixelXRange.length * pixelYRange.length * 4 * 2 + 64 * 1024),\n        );\n        const availableBytes = await this.spool.availableBytes();\n        if (availableBytes !== undefined && availableBytes < estimatedPageBytes) {\n          throw storagePressurePause(\n            payload.jobId,\n            outputIndex,\n            availableBytes,\n            estimatedPageBytes,\n          );\n        }'''
if old not in text:
    raise SystemExit("streamer loop marker missing")
text = text.replace(old, new, 1)
old = '''          const checkpoint = await writer.addJpegPage({\n            jpeg: raster.blob,\n            pixelWidth: canvasWidth,\n            pixelHeight: canvasHeight,\n            pageWidthPt: page.pageWidthPt,\n            pageHeightPt: page.pageHeightPt,\n            imageRectPt: page.imageRectPt,\n          });\n          const now = new Date();'''
new = '''          await writer.addJpegPage({\n            jpeg: raster.blob,\n            pixelWidth: canvasWidth,\n            pixelHeight: canvasHeight,\n            pageWidthPt: page.pageWidthPt,\n            pageHeightPt: page.pageHeightPt,\n            imageRectPt: page.imageRectPt,\n          });\n          // The OPFS page boundary is committed before the IndexedDB checkpoint. A crash\n          // between these operations is recovered by truncating back to the older checkpoint.\n          const checkpoint = await writer.commit();\n          const now = new Date();'''
if old not in text:
    raise SystemExit("streamer checkpoint marker missing")
text = text.replace(old, new, 1)
old = '''      const finalized = await writer.finalize();\n      const finalCheckpoint: PdfWriterCheckpoint = {\n        schemaVersion: 1,\n        jobId: payload.jobId,\n        outputArtifactId: payload.outputArtifactId,\n        spoolReference: finalized.checkpoint.spoolReference,\n        pagesWritten: finalized.checkpoint.pagesWritten,\n        totalPages: finalized.checkpoint.totalPages,\n        byteLength: finalized.checkpoint.byteLength,\n        createdAt: payload.createdAt,\n        updatedAt: new Date().toISOString(),\n        expiresAt: payload.expiresAt,\n      };\n      await this.checkpoints.put(finalCheckpoint);\n      const integrity = await assertStreamingPdfStructure(finalized.file.blob, writerPages.length);'''
new = '''      const finalized = await writer.finalize();\n      // Keep the last page-only durable checkpoint until job cleanup. If the background loses\n      // the completion response, recovery truncates the final xref/trailer and re-finalizes\n      // deterministically without re-rendering verified pages.\n      const integrity = await assertStreamingPdfStructure(finalized.file.blob, writerPages.length);'''
if old not in text:
    raise SystemExit("streamer final checkpoint marker missing")
text = text.replace(old, new, 1)
old = '''    } catch (error) {\n      await writer.abort().catch(() => undefined);\n      for (const reference of rasterReferences) {'''
new = '''    } catch (error) {\n      if (resumableStorageError(error)) {\n        await writer.suspend().catch(() => undefined);\n      } else {\n        await writer.abort().catch(() => undefined);\n        await this.checkpoints.delete(payload.jobId).catch(() => false);\n      }\n      for (const reference of rasterReferences) {'''
if old not in text:
    raise SystemExit("streamer catch marker missing")
text = text.replace(old, new, 1)
p.write_text(text)
